spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:h2:mem://localhost/~/jojoldu;MVCC=TRUE
    username: jojoldu
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: api